TEMP          EQU (65535 - 100)
TEMP1          EQU (65535 - 20000)
DISPLAY_IR equ 0FFC2H ;escrita instrucao no display.
DISPLAY_DR equ 0FFD2H ;escrita dado no display
DISPLAY_BF equ 0FFE2H ;leitura instrucao do display.
DISPLAY_R equ 0FFF2H ;leitura dado do display
DISPLAY_CONFIGURACAO equ 038H ; configura o display pra funcionar com 8 bits, usando 2 linhas e caracteres com tamanho 5x7 pontos 
DIPSPLAY_CONFIGURACAO_ENTRY_MODE EQU 06H; configura o entry mode do display
DISPLAY_CONFIGURACAO_DISPLAY EQU 0CH; configura on/off contro
DISPLAY_POS_INICIAL equ 80H ; posicao inical da memoria DDRAM do display (ou posicao zero do cursor)
MOTOR equ 0FFE6H



ORG 0h

Zera_Motor:
	CLR A ; Limpando A
	MOV P1,A; Zerando o Motor.... (Evitar aquecimento e rui´do!!) MOV A,#00H
	MOV DPTR,#MOTOR
	MOVX @DPTR,A
 	
Init_DISPAY: 	
	MOV DPTR, #DISPLAY_IR
	MOV A, #DISPLAY_CONFIGURACAO
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	MOV DPTR, #DISPLAY_IR
	MOV A, #DIPSPLAY_CONFIGURACAO_ENTRY_MODE
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	MOV DPTR, #DISPLAY_IR
	MOV A, #DISPLAY_CONFIGURACAO_DISPLAY
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	
	LJMP ANIMATION 
	
WRITE_CHAR:
	;MOV R0, #5H
	ACALL DISPLAY_POS
	MOV DPTR, #DISPLAY_DR
;	ACALL DISPLAY_BUSY
	ACALL TEMPO
	;MOV A, #'D'
	MOVX @DPTR, A
	RET
	
	
DISPLAY_POS:
	MOV DPTR, #DISPLAY_IR
	PUSH ACC
;	ACALL DISPLAY_BUSY
	ACALL TEMPO
	CLR A
	MOV A, #DISPLAY_POS_INICIAL
	;MOV R0,#05H
	ADD A, R0 ;LOCAL ONDE FICA A POSICAO DO CURSOR QUE VAI SER USADO APRA ESCRITA
	PUSH DPH
	PUSH DPL
	MOV DPTR, #Cursor_Ps
	MOVC A, @A+DPTR
	POP DPL
	POP DPH
	MOVX @DPTR, A
	POP ACC
	RET

DISPLAY_BUSY:
	MOV DPTR,#DISPLAY_BF ;Verifica se o Display está ocupado
	MOVX A,@DPTR
	JB ACC.7, DISPLAY_BUSY
	RET

ANIMATION:
	MOV A,#'A'
	MOV R0,#5
WRITESTR2:
	PUSH DPL
	PUSH DPH
	ACALL WRITE_CHAR
	POP DPH
	POP DPL
	INC R0
	ACALL TEMPO2
;	ACALL WRITE_CHAR
	LJMP WRITESTR2
	
	;INC DPTR
	;CLR A
	;MOVC A,@A+DPTR
	;CJNE A,#00,WRITESTR2


TEMPO:		;rotina de tempo(2000us)
    MOV R1, #1
LOOP:
    MOV TMOD,#00000001B
    MOV TL0,#LOW(TEMP)
    MOV TH0,#HIGH(TEMP)
    SETB TR0
    JNB TF0,$
    CLR TR0
    CLR TF0
    DJNZ R1,LOOP
    RET
    
TEMPO2:		;rotina de tempo(2000us)
    MOV R1, #5
LOOP1:
    MOV TMOD,#00000001B
    MOV TL0,#LOW(TEMP1)
    MOV TH0,#HIGH(TEMP1)
    SETB TR0
    JNB TF0,$
    CLR TR0
    CLR TF0
    DJNZ R1,LOOP1
    RET
	
Cursor_Ps: db 00H, 01H, 02H, 03H, 04H, 05H, 06H, 07H, 08H, 09H, 0AH, 0BH, 0CH, 0DH, 0EH, 0FH, 40H, 41H, 42H, 43H, 44H, 45H, 46H, 47H, 48H, 49H, 4AH, 4BH, 4CH, 4DH, 4EH, 4FH,10H, 11H, 12H, 13H, 14H, 15H, 16H, 17H, 18H, 19H, 1AH, 1BH, 1CH, 1DH, 1EH, 1FH, 50H, 51H, 52H, 53H, 54H, 55H, 56H, 57H, 58H, 59H, 5AH, 5BH, 5CH, 5DH, 5EH, 5FH

END