TEMP          EQU (65535 - 922)
TEMP1          EQU (65535 - 800)
DISPLAY_IR equ 0FFC2H ;escrita instrucao no display.
DISPLAY_DR equ 0FFD2H ;escrita dado no display
DISPLAY_BF equ 0FFE2H ;leitura instrucao do display.
DISPLAY_R equ 0FFF2H ;leitura dado do display
DISPLAY_CONFIGURACAO equ 038H ; configura o display pra funcionar com 8 bits, usando 2 linhas e caracteres com tamanho 5x7 pontos 
DIPSPLAY_CONFIGURACAO_ENTRY_MODE EQU 06H; configura o entry mode do display
DISPLAY_CONFIGURACAO_DISPLAY EQU 0CH; configura on/off contro
DISPLAY_POS_INICIAL equ 80H ; posicao inical da memoria DDRAM do display (ou posicao zero do cursor)
TECLAAUX equ 11H
TECLADO equ 0FFE3H
LER_AD EQU 0FFC5H
AD EQU 50H
MOTOR equ 0FFE6H



ORG 0h

Zera_Motor:
	CLR A ; Limpando A
	MOV P1,A; Zerando o Motor.... (Evitar aquecimento e rui�do!!) MOV A,#00H
	MOV DPTR,#MOTOR
	MOVX @DPTR,A
 	
Init_DISPAY:
	MOV DPTR, #DISPLAY_IR
	MOV A, #DISPLAY_CONFIGURACAO
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	MOV DPTR, #DISPLAY_IR
	MOV A, #DIPSPLAY_CONFIGURACAO_ENTRY_MODE
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	MOV DPTR, #DISPLAY_IR
	MOV A, #DISPLAY_CONFIGURACAO_DISPLAY
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY

	ACALL SERIAL_CONFIG
	
	;MOV DPTR, #DISPLAY_IR
	;MOV A, 
	
	LJMP ANIMATION
    
AD_READER:
	PUSH ACC
	PUSH DPH
	PUSH DPL
	MOV A,#40H
	MOV DPTR,#LER_AD
	MOVX @DPTR,A
	ACALL TEMPO
	MOVX A,@DPTR
	MOV AD, A
	;MOV P1, AD
	POP DPL
	POP DPH
	POP ACC
	RET
	
WRITE_CHAR:
	;MOV A, #'A'
	ACALL DISPLAY_POS
	MOV DPTR, #DISPLAY_DR
	ACALL TEMPO
	MOVX @DPTR, A
	RET
	
	
DISPLAY_POS:
	MOV DPTR, #DISPLAY_IR
	PUSH ACC
;	ACALL DISPLAY_BUSY
	ACALL TEMPO
	CLR A
	MOV R2, #DISPLAY_POS_INICIAL
	;MOV R0,#05H
	PUSH DPH
	PUSH DPL
	MOV A, R0
	ACALL TEMPO
;	MOV DPTR, #Cursor_Ps
;	MOV DPTR, #Cursor
	MOV DPTR, #ANIMACAO
	ACALL TEMPO
	MOVC A, @A+DPTR
	ACALL TEMPO
	ADD A, R2 ;LOCAL ONDE FICA A POSICAO DO CURSOR QUE VAI SER USADO APRA ESCRITA
	POP DPL
	POP DPH
	ACALL TEMPO
	MOVX @DPTR, A
	POP ACC
	RET

DISPLAY_BUSY:
	MOV DPTR,#DISPLAY_BF ;Verifica se o Display est� ocupado
	MOVX A,@DPTR
	JB ACC.7, DISPLAY_BUSY
	RET
	
DISPLAY_CLEAR:
	PUSH DPL
	PUSH DPH
	MOV DPTR, #DISPLAY_IR
	MOV A, #01H
	MOVX @DPTR, A
	ACALL DISPLAY_BUSY
	POP DPH
	POP DPL
	RET

TRAVA_S:
    JNB RI, $
    CLR RI
	MOV A,SBUF
    CJNE A,#'P',TRAVA_S_RELOAD_CONFIG; Pressionou tecla "1"?
    RET
TRAVA_S_RELOAD_CONFIG:
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	LJMP TRAVA_S

TRAVA2_S:
	INC R0
	MOV A,#'A'
	ACALL WRITE_CHAR
	ACALL TEMPO3
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	PUSH ACC
TRAVA_VS:
	JNB RI, $
	CLR RI
	MOV A,SBUF
	CJNE A,#'P', INCREMENTA_S
	POP ACC
	RET
INCREMENTA_S:
	CJNE R0,#16, VERIFICA_INC_S
	MOV R0,#0
	ACALL DISPLAY_CLEAR
VERIFICA_INC_S:
	CJNE A,#'A', TRAVA_V_S_RELOAD_CONFIG
	POP ACC
	LJMP TRAVA2_S
TRAVA_V_S_RELOAD_CONFIG:
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	LJMP TRAVA_V_S

TRAVA3_S:
	MOV A,#' '
	DEC R0
	ACALL WRITE_CHAR
	ACALL TEMPO3
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	PUSH ACC
TRAVA_VD_S:
	JNB RI, $
	CLR RI
	MOV A,SBUF
	CJNE A,#'P', DECREMENTA_S
	POP ACC
	RET
DECREMENTA_S:
	CJNE R0,#0, VERIFICA_DEC_S
	LJMP TRAVA_VD_S
VERIFICA_DEC_S:
	CJNE A,#'R', TRAVA_VD_S
	POP ACC
	LJMP TRAVA3_S
TRAVA_VD_S_RELOAD_CONFIG:
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	LJMP TRAVA_VD_S_RELOAD_CONFIG

VERIFICA_SERIAL:
	JNB RI, RETORNA_S
	CLR RI
	MOV P1, #'U'
	PUSH ACC
	MOV A,SBUF
	CJNE A,#'P',TRT2_S; Pressionou tecla "1" para play/pause?
	ACALL TRAVA_S
	TRT2_S: CJNE A,#'A',TR3_S
	ACALL TRAVA2_S
	MOV P1,A
	TR3_S: CJNE A,#'R',TR6_S
	MOV P1,A
	ACALL TRAVA3_S
	TR6_S: POP ACC
RETORNA_S:
	RET
ANIMATION:
	MOV A,#'A'
	MOV R0,#0
WRITESTR2:
	ACALL AD_READER
	;ACALL TECLADO_READ
	;ACALL SERIAL_CONFIG;TLAVEZ SEJA NECESSARIA, POR ISSO COMENTEI
	;ACALL TEMPO2
	ACALL VERIFICA_SERIAL
	ACALL TEMPO2
	;MOV DPTR, #0
;	ACALL DISPLAY_CLEAR
	MOV A,#'A'
	PUSH DPL
	PUSH DPH
;	MOV DPTR, #0
	ACALL WRITE_CHAR
	POP DPH
	POP DPL
;	MOV DPTR, #0
	ACALL TEMPO2
	INC R0
	CJNE R0, #16, WRITESTR2
	MOV R0,#0
	ACALL DISPLAY_CLEAR
	LJMP ANIMATION
	;LJMP WRITESTR2
	
	;INC DPTR
	;CLR A
	;MOVC A,@A+DPTR
	;CJNE A,#00,WRITESTR2

SERIAL_CONFIG:
	MOV SCON,#50H
	MOV TMOD,#20H; Serial
	MOV TH1,#232
	MOV TL1,#232
	SETB TR1
	;SETB REN; Serial
	RET


TEMPO:		;rotina de tempo(2000us)
    MOV R1, #1
LOOP:
    MOV TMOD,#00000001B
    MOV TL0,#LOW(TEMP)
    MOV TH0,#HIGH(TEMP)
    SETB TR0
    JNB TF0,$
    CLR TR0
    CLR TF0
    DJNZ R1,LOOP
    RET
    
TEMPO2:		;rotina de tempo(2000us)
    MOV R1, AD
LOOP1:
    MOV TMOD,#00000001B
    MOV TL0,#LOW(TEMP1)
    MOV TH0,#HIGH(TEMP1)
    SETB TR0
    JNB TF0,$
    CLR TR0
    CLR TF0
    DJNZ R1,LOOP1
    RET
    
TEMPO3:		;rotina de tempo(2000us)
    MOV R1, #2
LOOP2:
    MOV TMOD,#00000001B
    MOV TL0,#LOW(TEMP1)
    MOV TH0,#HIGH(TEMP1)
    SETB TR0
    JNB TF0,$
    CLR TR0
    CLR TF0
    DJNZ R1,LOOP2
    RET
	
;Cursor_Ps: db 00H, 01H, 02H, 03H, 04H, 05H, 06H, 07H, 08H, 09H, 0AH, 0BH, 0CH, 0DH, 0EH, 0FH, 40H, 41H, 42H, 43H, 44H, 45H, 46H, 47H, 48H, 49H, 4AH, 4BH, 4CH, 4DH, 4EH, 4FH, 10H, 11H, 12H, 13H, 14H, 15H, 16H, 17H, 18H, 19H, 1AH, 1BH, 1CH, 1DH, 1EH, 1FH, 50H, 51H, 52H, 53H, 54H, 55H, 56H, 57H, 58H, 59H, 5AH, 5BH, 5CH, 5DH, 5EH, 5FH

;Cursor: db 80H, 81H, 82H, 83H, 84H, 85H, 86H, 87H, 88H, 89H, 8AH, 8BH, 8CH, 8DH, 8EH, 8FH, C0H, C1H, C2H, C3H, C4H, C5H, C6H, C7H, C8H, C9H, CAH, CBH, CCH, CDH, CEH, CFH, 90H, 91H, 92H, 93H, 94H, 95H, 96H, 97H, 98H, 99H, 9AH, 9BH, 9CH, 9DH, 9EH, 9FH, D0H, D1H, D2H, D3H, D4H, D5H, D6H, D7H, D8H, D9H, DAH, DBH, DCH, DDH, DEH, DFH

;ANIMACAO: db 10H, 11H, 12H, 13H, 14H, 15H, 16H, 17H, 18H, 19H, 1AH, 1BH, 1CH, 1DH, 1EH, 1FH, 50H, 51H, 52H, 53H, 54H, 55H, 56H, 57H, 58H, 59H, 5AH, 5BH, 5CH, 5DH, 5EH, 5FH

ANIMACAO: db 08H, 09H, 0AH, 4BH, 1BH, 5AH, 59H, 58H, 17H, 47H, 08H, 49H, 19H, 49H, 19H, 49H, 19H

END